---
- name: Ntp configuring
  hosts: all
  become: true
  vars:
    timesync_ntp_servers:
      - hostname: 10.10.10.10
        iburst: true
  roles:
    - rhel-system-roles.timesync
  tasks:
    - command: timedatectl set-ntp true
   
